server:
  port: 8095


spring:
  cloud:
    alibaba:
      seata:
        tx-service-group: huihui_test_tx_group
  application:
    name: service-verification-code
  #数据源配置
  datasource:
    druid:
      name: mysql
      url: jdbc:mysql://localhost:3306/seata-server
      username: root
      password: ymh96122
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 100
      initial-size: 1
      min-idle: 1
      max-wait: 60000
  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 30000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.huihui.aligo.model

eureka:
  instance:
    hostname: service-verification-code
    prefer-ip-address: true
    metadata-map:
      version: v1
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
      #是否从从注册中心获取服务信息
    fetch-registry: true
    #是否注册到注册中心
    register-with-eureka: true
    #定时从注册中心拉取注册表的间隔，默认30s
    registry-fetch-interval-seconds: 30

