server:
  port: 8093

spring:
  #seata配置
  cloud:
    alibaba:
      seata:
        tx-service-group: huihui_test_tx_group
  application:
    name: api-passenger
  #数据源配置
  datasource:
    druid:
      name: mysql
      url: jdbc:mysql://localhost:3306/seata-server
      username: root
      password: ymh96122
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 100
      initial-size: 1
      min-idle: 1
      max-wait: 60000





eureka:
  instance:
    hostname: api-passenger
    #以IP地址注册到服务中心（否则报找不到服务错误）
    prefer-ip-address: true
    metadata-map:
      version: v1
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
      #是否从从注册中心获取服务信息
    fetch-registry: true
    #是否注册到注册中心
    register-with-eureka: true
    #定时从注册中心拉取注册表的间隔，默认30s
    registry-fetch-interval-seconds: 30


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.huihui.aligo.model

