server:
  port: 8093

spring:
  application:
    name: api-passenger

eureka:
  instance:
    hostname: api-passenger
    #以IP地址注册到服务中心（否则报找不到服务错误）
    prefer-ip-address: true
    metadata-map:
      version: v1
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
      #是否从从注册中心获取服务信息
    fetch-registry: true
    #是否注册到注册中心
    register-with-eureka: true
    #定时从注册中心拉取注册表的间隔，默认30s
    registry-fetch-interval-seconds: 30

