server:
  port: 8090

spring:
  application:
    name: service-sms

eureka:
  instance:
    hostname: service-sms
  client:
    service-url:
      defaultZone: http://eurekaOne:8888/eureka/
      #是否从从注册中心获取服务信息
    fetch-registry: true
    #是否注册到注册中心
    register-with-eureka: true
    #定时从注册中心拉取注册表的间隔，默认30s
    registry-fetch-interval-seconds: 30
